
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ButtonGroup;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author markhew
 */
public class NewJobView extends javax.swing.JFrame {

    /**
     * Creates new form NewJobView
     */
    private ArrayList<ImageIcon> selectedTabs;
    private ArrayList<ImageIcon> nonSelectedTabs;
    private final int defaultWidth = 560;
    private final int defaultHeight = 320;
    private final int viewHeight = 570;
    private final int viewWidth = 230;
    private final int viewWidthExtended = 680;
    private double aspectRatio;
    private SourceView sv;
    private MainView parent;

    public NewJobView(MainView parent) {
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/handbrake-Icon.png"));
        this.setIconImage(icon.getImage());
        initComponents();
        this.setResizable(false);
        setImages();
        addCustomization();
        this.setSize(viewWidth, viewHeight);
        this.parent = parent;
        sv = new SourceView();
        //Setting the height and width in the picture section for advanced
        aspectRatio = (double) defaultWidth / (double) defaultHeight;
        sizeLabel.setText(String.valueOf(defaultWidth) + "x" + String.valueOf(defaultHeight));
        ratioLabel.setText(String.valueOf(aspectRatio));
        outWidthField.setText(String.valueOf(defaultWidth));
        outHeightField.setText(String.valueOf(defaultHeight));
        groupButtons();
    }

    //Adds customization to the components
    private void addCustomization() {
        advancedToggleButton.setOpaque(false);
        optionsBtn.setOpaque(false);
        advancedToggleButton.setContentAreaFilled(false);
        optionsBtn.setContentAreaFilled(false);

    }

    private void setImages() {
        //Setting the index for the image icons is vital as image will match the tab
        selectedTabs = new ArrayList<ImageIcon>();
        nonSelectedTabs = new ArrayList<ImageIcon>();

        nonSelectedTabs.add(new ImageIcon(getClass().getResource("/Images/VideoTab.png")));
        nonSelectedTabs.add(new ImageIcon(getClass().getResource("/Images/PictureTab.png")));
        nonSelectedTabs.add(new ImageIcon(getClass().getResource("/Images/AudioTab.png")));
        nonSelectedTabs.add(new ImageIcon(getClass().getResource("/Images/SubtitlesTab.png")));
        nonSelectedTabs.add(new ImageIcon(getClass().getResource("/Images/ChaptersTab.png")));
        nonSelectedTabs.add(new ImageIcon(getClass().getResource("/Images/OptimiseTab.png")));
        nonSelectedTabs.add(new ImageIcon(getClass().getResource("/Images/FiltersTab.png")));

        selectedTabs.add(new ImageIcon(getClass().getResource("/Images/VideoTab2.png")));
        selectedTabs.add(new ImageIcon(getClass().getResource("/Images/PictureTab2.png")));
        selectedTabs.add(new ImageIcon(getClass().getResource("/Images/AudioTab2.png")));
        selectedTabs.add(new ImageIcon(getClass().getResource("/Images/SubtitlesTab2.png")));
        selectedTabs.add(new ImageIcon(getClass().getResource("/Images/ChaptersTab2.png")));
        selectedTabs.add(new ImageIcon(getClass().getResource("/Images/OptimiseTab2.png")));
        selectedTabs.add(new ImageIcon(getClass().getResource("/Images/FiltersTab2.png")));

    }

    private void groupButtons() {
        ButtonGroup picbg = new ButtonGroup();
        ButtonGroup vidbg = new ButtonGroup();
        picbg.add(automaticRadio);
        picbg.add(customRadio);
        vidbg.add(constantFrameRateRadio);
        vidbg.add(variableFrameRateRadio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        outputWidthField = new javax.swing.JTextField();
        outputHeightField = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jSpinner1 = new javax.swing.JSpinner();
        topField = new javax.swing.JFormattedTextField();
        rightField = new javax.swing.JFormattedTextField();
        leftField = new javax.swing.JFormattedTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        popupMenu1 = new java.awt.PopupMenu();
        JobPanel = new javax.swing.JPanel();
        jobPanel = new javax.swing.JPanel();
        doneBtn = new javax.swing.JButton();
        previewBtn = new javax.swing.JButton();
        sourceLabel = new javax.swing.JLabel();
        sourceTextLabel = new javax.swing.JLabel();
        srcBtn = new javax.swing.JButton();
        destinationLabel = new javax.swing.JLabel();
        destinationTxtLabel = new javax.swing.JLabel();
        destBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        choiceComboBox = new javax.swing.JComboBox();
        angleComboBox = new javax.swing.JComboBox();
        fromComboBox = new javax.swing.JComboBox();
        toComboBox = new javax.swing.JComboBox();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        outputPresetComboBox = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        advancedToggleButton = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        optionsBtn = new javax.swing.JButton();
        advancedPanel = new javax.swing.JPanel();
        TabbedPane = new javax.swing.JTabbedPane();
        videoPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        videoFrameComboBox = new javax.swing.JComboBox();
        frameRateComboBox = new javax.swing.JComboBox();
        constantFrameRateRadio = new javax.swing.JRadioButton();
        variableFrameRateRadio = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        aveBitRateField = new javax.swing.JTextField();
        passEncodingCheckBox = new javax.swing.JCheckBox();
        turboFirstPassCheckbox = new javax.swing.JCheckBox();
        picturePanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        sizeLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ratioLabel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        outWidthField = new javax.swing.JFormattedTextField();
        outHeightField = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        anamorphicComboBox = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        modulusComboBox = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        automaticRadio = new javax.swing.JRadioButton();
        customRadio = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        topSpinner = new javax.swing.JSpinner();
        leftSpinner = new javax.swing.JSpinner();
        rightSpinner = new javax.swing.JSpinner();
        bottomSpinner = new javax.swing.JSpinner();
        audioPanel = new javax.swing.JPanel();
        subtitlesPanel = new javax.swing.JPanel();
        chaptersPanel = new javax.swing.JPanel();
        OptimisePanel = new javax.swing.JPanel();
        filterPanel = new javax.swing.JPanel();
        detelecineCheckbox = new javax.swing.JCheckBox();
        decombCheckbox = new javax.swing.JCheckBox();
        deinterfaceCheckbox = new javax.swing.JCheckBox();
        denoiseCheckbox = new javax.swing.JCheckBox();
        jLabel32 = new javax.swing.JLabel();
        deblockingSlider = new javax.swing.JSlider();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        saveBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("jButton1");

        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        outputWidthField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                outputWidthFieldKeyPressed(evt);
            }
        });

        jRadioButton1.setText("jRadioButton1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel27.setText("Detelecine");

        jLabel28.setText("Decomb");

        jLabel29.setText("Deinterface");

        jLabel30.setText("Denoise");

        jLabel31.setText("Deblocking");

        jToolBar1.setRollover(true);

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(81, 158, 184));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        JobPanel.setBackground(new java.awt.Color(63, 160, 186));

        jobPanel.setBackground(new java.awt.Color(63, 160, 186));
        jobPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jobPanel.setName(""); // NOI18N

        doneBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Done.png"))); // NOI18N
        doneBtn.setBorderPainted(false);
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });

        previewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Preview.png"))); // NOI18N
        previewBtn.setBorderPainted(false);
        previewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewBtnActionPerformed(evt);
            }
        });

        sourceLabel.setForeground(new java.awt.Color(255, 255, 255));
        sourceLabel.setText("Source");

        sourceTextLabel.setBackground(new java.awt.Color(0, 102, 102));
        sourceTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        sourceTextLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        srcBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/File.png"))); // NOI18N
        srcBtn.setBorderPainted(false);
        srcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcBtnActionPerformed(evt);
            }
        });

        destinationLabel.setForeground(new java.awt.Color(255, 255, 255));
        destinationLabel.setText("Destination");

        destinationTxtLabel.setForeground(new java.awt.Color(255, 255, 255));
        destinationTxtLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        destBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/File.png"))); // NOI18N
        destBtn.setBorderPainted(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Selection");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Choice");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Angle");

        choiceComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chapters", "Seconds", "Frames" }));

        angleComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1" }));

        fromComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1" }));

        toComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1" }));

        fromLabel.setForeground(new java.awt.Color(255, 255, 255));
        fromLabel.setText("From");

        toLabel.setForeground(new java.awt.Color(255, 255, 255));
        toLabel.setText("To");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Output Preset");

        outputPresetComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MP4", "MKV" }));

        jPanel3.setBackground(new java.awt.Color(99, 162, 185));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        advancedToggleButton.setBackground(new java.awt.Color(255, 255, 255));
        advancedToggleButton.setForeground(new java.awt.Color(255, 255, 255));
        advancedToggleButton.setText("Advanced");
        advancedToggleButton.setBorder(null);
        advancedToggleButton.setBorderPainted(false);
        advancedToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advancedToggleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(advancedToggleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(advancedToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(99, 162, 185));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        optionsBtn.setForeground(new java.awt.Color(255, 255, 255));
        optionsBtn.setText("Options");
        optionsBtn.setBorderPainted(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionsBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(optionsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jobPanelLayout = new javax.swing.GroupLayout(jobPanel);
        jobPanel.setLayout(jobPanelLayout);
        jobPanelLayout.setHorizontalGroup(
            jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jobPanelLayout.createSequentialGroup()
                .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jobPanelLayout.createSequentialGroup()
                        .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jobPanelLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(sourceLabel))
                            .addGroup(jobPanelLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(outputPresetComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jobPanelLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(destinationLabel))
                            .addGroup(jobPanelLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jobPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jobPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jobPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(121, 121, 121))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jobPanelLayout.createSequentialGroup()
                                        .addComponent(destinationTxtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(destBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jobPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jobPanelLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jobPanelLayout.createSequentialGroup()
                                                .addComponent(doneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(previewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jobPanelLayout.createSequentialGroup()
                                                .addComponent(sourceTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(srcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jobPanelLayout.createSequentialGroup()
                                        .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(choiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(toComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(angleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)))
                                    .addGroup(jobPanelLayout.createSequentialGroup()
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jobPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fromLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toLabel)
                .addGap(56, 56, 56))
        );
        jobPanelLayout.setVerticalGroup(
            jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jobPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(doneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sourceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sourceTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(destinationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(destinationTxtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromLabel)
                    .addComponent(toLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputPresetComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        advancedPanel.setBackground(new java.awt.Color(63, 160, 186));
        advancedPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        advancedPanel.setPreferredSize(new java.awt.Dimension(375, 530));

        TabbedPane.setBackground(new java.awt.Color(63, 160, 186));
        TabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        TabbedPane.setToolTipText("");
        TabbedPane.setOpaque(true);
        TabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TabbedPaneStateChanged(evt);
            }
        });

        videoPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Frames");

        jLabel6.setText("Video");

        jLabel7.setText("Codec");

        jLabel8.setText("Framerate");

        videoFrameComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "H.264(x264)", "MPEG-4 ", "MPEG-2", " " }));

        frameRateComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Same as source", "10", "15", "30", "35", "40", "45", "50" }));

        constantFrameRateRadio.setText("Constant Framerate");

        variableFrameRateRadio.setText("Variable Framerate");

        jLabel9.setText("Quality");

        jLabel10.setText("Full RF");

        jLabel11.setText("Lossless");

        jLabel12.setText("Average Bitrate (kbps)");

        passEncodingCheckBox.setText("2-Pass Encoding");

        turboFirstPassCheckbox.setText("Turbo First Pass");

        javax.swing.GroupLayout videoPanelLayout = new javax.swing.GroupLayout(videoPanel);
        videoPanel.setLayout(videoPanelLayout);
        videoPanelLayout.setHorizontalGroup(
            videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(videoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, videoPanelLayout.createSequentialGroup()
                        .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(videoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aveBitRateField))
                            .addGroup(videoPanelLayout.createSequentialGroup()
                                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(frameRateComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(videoFrameComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(videoPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(constantFrameRateRadio)
                                    .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11)
                                        .addComponent(variableFrameRateRadio)))))
                        .addGap(16, 16, 16))
                    .addGroup(videoPanelLayout.createSequentialGroup()
                        .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(videoPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(videoPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(turboFirstPassCheckbox)
                    .addComponent(passEncodingCheckBox))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        videoPanelLayout.setVerticalGroup(
            videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(videoFrameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(frameRateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(constantFrameRateRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(variableFrameRateRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(aveBitRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passEncodingCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(turboFirstPassCheckbox)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        TabbedPane.addTab("", new javax.swing.ImageIcon(getClass().getResource("/Images/VideoTab2.png")), videoPanel); // NOI18N

        picturePanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setText("Sizing");

        jLabel14.setText("Initial Size :");

        sizeLabel.setText("560 x 320");

        jLabel17.setText("Aspect Ratio :");

        ratioLabel.setText("1.75");

        jLabel18.setText("Ouput Width :");

        jLabel19.setText("Output Height :");

        try {
            outWidthField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        outWidthField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                outWidthFieldFocusLost(evt);
            }
        });

        try {
            outHeightField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel20.setText("Anamorphic :");

        anamorphicComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Loose", "Strict", "Custom" }));

        jLabel21.setText("Modulus :");

        modulusComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "16", "8", "4", "2" }));

        jLabel22.setText("Cropping ");

        automaticRadio.setText("Automatic");

        customRadio.setText("Custom (Pixels)");

        jLabel23.setText("Top");

        jLabel24.setText("Right");

        jLabel25.setText("Left");

        jLabel26.setText("Bottom");

        javax.swing.GroupLayout picturePanelLayout = new javax.swing.GroupLayout(picturePanel);
        picturePanel.setLayout(picturePanelLayout);
        picturePanelLayout.setHorizontalGroup(
            picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(picturePanelLayout.createSequentialGroup()
                .addGroup(picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(picturePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(picturePanelLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16))
                            .addGroup(picturePanelLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ratioLabel))
                            .addGroup(picturePanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(picturePanelLayout.createSequentialGroup()
                                        .addGroup(picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(outWidthField)
                                            .addComponent(outHeightField)))
                                    .addComponent(jLabel22)
                                    .addGroup(picturePanelLayout.createSequentialGroup()
                                        .addGroup(picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel20))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(anamorphicComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(modulusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(picturePanelLayout.createSequentialGroup()
                                        .addGroup(picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(picturePanelLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel25))
                                            .addGroup(picturePanelLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(leftSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bottomSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(topSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel26))
                                        .addGroup(picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(picturePanelLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel24))
                                            .addGroup(picturePanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(rightSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addComponent(automaticRadio)
                    .addComponent(customRadio)
                    .addGroup(picturePanelLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel23)))
                .addGap(0, 172, Short.MAX_VALUE))
        );
        picturePanelLayout.setVerticalGroup(
            picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(picturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(sizeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(ratioLabel))
                .addGap(21, 21, 21)
                .addGroup(picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(outWidthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(outHeightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(anamorphicComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(modulusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(automaticRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addGap(2, 2, 2)
                .addGroup(picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(picturePanelLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(leftSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rightSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(picturePanelLayout.createSequentialGroup()
                        .addGroup(picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(topSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottomSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabbedPane.addTab("", new javax.swing.ImageIcon(getClass().getResource("/Images/PictureTab.png")), picturePanel); // NOI18N

        audioPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout audioPanelLayout = new javax.swing.GroupLayout(audioPanel);
        audioPanel.setLayout(audioPanelLayout);
        audioPanelLayout.setHorizontalGroup(
            audioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );
        audioPanelLayout.setVerticalGroup(
            audioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        TabbedPane.addTab("", new javax.swing.ImageIcon(getClass().getResource("/Images/AudioTab.png")), audioPanel); // NOI18N

        subtitlesPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout subtitlesPanelLayout = new javax.swing.GroupLayout(subtitlesPanel);
        subtitlesPanel.setLayout(subtitlesPanelLayout);
        subtitlesPanelLayout.setHorizontalGroup(
            subtitlesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );
        subtitlesPanelLayout.setVerticalGroup(
            subtitlesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        TabbedPane.addTab("", new javax.swing.ImageIcon(getClass().getResource("/Images/SubtitlesTab.png")), subtitlesPanel); // NOI18N

        chaptersPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout chaptersPanelLayout = new javax.swing.GroupLayout(chaptersPanel);
        chaptersPanel.setLayout(chaptersPanelLayout);
        chaptersPanelLayout.setHorizontalGroup(
            chaptersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );
        chaptersPanelLayout.setVerticalGroup(
            chaptersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        TabbedPane.addTab("", new javax.swing.ImageIcon(getClass().getResource("/Images/ChaptersTab.png")), chaptersPanel); // NOI18N

        OptimisePanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout OptimisePanelLayout = new javax.swing.GroupLayout(OptimisePanel);
        OptimisePanel.setLayout(OptimisePanelLayout);
        OptimisePanelLayout.setHorizontalGroup(
            OptimisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );
        OptimisePanelLayout.setVerticalGroup(
            OptimisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        TabbedPane.addTab("", new javax.swing.ImageIcon(getClass().getResource("/Images/OptimiseTab.png")), OptimisePanel); // NOI18N

        filterPanel.setBackground(new java.awt.Color(255, 255, 255));

        detelecineCheckbox.setText("Detelecine");

        decombCheckbox.setText("Decomb");

        deinterfaceCheckbox.setText("Deinterface");

        denoiseCheckbox.setText("Denoise");

        jLabel32.setText("Deblocking");

        jLabel33.setText("Off");

        jLabel34.setText("Full");

        jCheckBox1.setText("Grayscale Filter");

        javax.swing.GroupLayout filterPanelLayout = new javax.swing.GroupLayout(filterPanel);
        filterPanel.setLayout(filterPanelLayout);
        filterPanelLayout.setHorizontalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(denoiseCheckbox)
                    .addComponent(jLabel32)
                    .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(filterPanelLayout.createSequentialGroup()
                            .addComponent(jLabel33)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel34))
                        .addComponent(deblockingSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBox1)
                    .addComponent(detelecineCheckbox)
                    .addComponent(decombCheckbox)
                    .addComponent(deinterfaceCheckbox))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        filterPanelLayout.setVerticalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(detelecineCheckbox)
                .addGap(18, 18, 18)
                .addComponent(decombCheckbox)
                .addGap(18, 18, 18)
                .addComponent(deinterfaceCheckbox)
                .addGap(18, 18, 18)
                .addComponent(denoiseCheckbox)
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deblockingSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addGap(64, 64, 64)
                .addComponent(jCheckBox1)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        TabbedPane.addTab("", new javax.swing.ImageIcon(getClass().getResource("/Images/FiltersTab.png")), filterPanel); // NOI18N

        saveBtn.setBackground(new java.awt.Color(81, 158, 184));
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save.png"))); // NOI18N
        saveBtn.setBorderPainted(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout advancedPanelLayout = new javax.swing.GroupLayout(advancedPanel);
        advancedPanel.setLayout(advancedPanelLayout);
        advancedPanelLayout.setHorizontalGroup(
            advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advancedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                    .addGroup(advancedPanelLayout.createSequentialGroup()
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        advancedPanelLayout.setVerticalGroup(
            advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advancedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout JobPanelLayout = new javax.swing.GroupLayout(JobPanel);
        JobPanel.setLayout(JobPanelLayout);
        JobPanelLayout.setHorizontalGroup(
            JobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JobPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jobPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(advancedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JobPanelLayout.setVerticalGroup(
            JobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JobPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(advancedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                    .addComponent(jobPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(63, 160, 186));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JobPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JobPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void outputWidthFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_outputWidthFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputWidthFieldKeyPressed

    private void outWidthFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_outWidthFieldFocusLost
        // TODO add your handling code here:
        int newWidth = Integer.parseInt(outWidthField.getText());
        int height = Integer.parseInt(outHeightField.getText());
        aspectRatio = (double) newWidth / (double) height;

        sizeLabel.setText(String.valueOf(newWidth) + "x" + String.valueOf(height));
        ratioLabel.setText(String.valueOf(aspectRatio));
    }//GEN-LAST:event_outWidthFieldFocusLost

    private void advancedToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advancedToggleButtonActionPerformed
        // TODO add your handling code here:
        if (advancedToggleButton.isSelected()) {
            advancedPanel.setVisible(true);
            this.setSize(viewWidthExtended, viewHeight);
            advancedToggleButton.setText("Simplify");
        } else {
            advancedPanel.setVisible(false);
            this.setSize(viewWidth, viewHeight);
            advancedToggleButton.setText("Advanced");

        }
    }//GEN-LAST:event_advancedToggleButtonActionPerformed

    private void srcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcBtnActionPerformed
        // TODO add your handling code here:
        sv.setVisible(true);

    }//GEN-LAST:event_srcBtnActionPerformed

    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
        //Add the job to the queue after that dispose of the jframe
        this.setVisible(false);
        this.dispose();
        this.parent.resetToggleBtn();
    }//GEN-LAST:event_doneBtnActionPerformed

    private void TabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TabbedPaneStateChanged
        // TODO add your handling code here:
        int tabCount = TabbedPane.getTabCount();

        if (tabCount > 1) {
            int selectedTab = TabbedPane.getSelectedIndex();
            for (int i = 0; i < tabCount; i++) {
                if (i == selectedTab) {
                    TabbedPane.setIconAt(i, selectedTabs.get(i));
                } else {
                    TabbedPane.setIconAt(i, nonSelectedTabs.get(i));
                }
            }
        }
    }//GEN-LAST:event_TabbedPaneStateChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.parent.resetToggleBtn();
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void previewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Not implemented.");
    }//GEN-LAST:event_previewBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Not implemented.");
    }//GEN-LAST:event_saveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JobPanel;
    private javax.swing.JPanel OptimisePanel;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JPanel advancedPanel;
    private javax.swing.JToggleButton advancedToggleButton;
    private javax.swing.JComboBox anamorphicComboBox;
    private javax.swing.JComboBox angleComboBox;
    private javax.swing.JPanel audioPanel;
    private javax.swing.JRadioButton automaticRadio;
    private javax.swing.JTextField aveBitRateField;
    private javax.swing.JSpinner bottomSpinner;
    private javax.swing.JPanel chaptersPanel;
    private javax.swing.JComboBox choiceComboBox;
    private javax.swing.JRadioButton constantFrameRateRadio;
    private javax.swing.JRadioButton customRadio;
    private javax.swing.JSlider deblockingSlider;
    private javax.swing.JCheckBox decombCheckbox;
    private javax.swing.JCheckBox deinterfaceCheckbox;
    private javax.swing.JCheckBox denoiseCheckbox;
    private javax.swing.JButton destBtn;
    private javax.swing.JLabel destinationLabel;
    private javax.swing.JLabel destinationTxtLabel;
    private javax.swing.JCheckBox detelecineCheckbox;
    private javax.swing.JButton doneBtn;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JComboBox frameRateComboBox;
    private javax.swing.JComboBox fromComboBox;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel jobPanel;
    private javax.swing.JFormattedTextField leftField;
    private javax.swing.JSpinner leftSpinner;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JComboBox modulusComboBox;
    private javax.swing.JButton optionsBtn;
    private javax.swing.JFormattedTextField outHeightField;
    private javax.swing.JFormattedTextField outWidthField;
    private javax.swing.JTextField outputHeightField;
    private javax.swing.JComboBox outputPresetComboBox;
    private javax.swing.JTextField outputWidthField;
    private javax.swing.JCheckBox passEncodingCheckBox;
    private javax.swing.JPanel picturePanel;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JButton previewBtn;
    private javax.swing.JLabel ratioLabel;
    private javax.swing.JFormattedTextField rightField;
    private javax.swing.JSpinner rightSpinner;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JLabel sourceLabel;
    private javax.swing.JLabel sourceTextLabel;
    private javax.swing.JButton srcBtn;
    private javax.swing.JPanel subtitlesPanel;
    private javax.swing.JComboBox toComboBox;
    private javax.swing.JLabel toLabel;
    private javax.swing.JFormattedTextField topField;
    private javax.swing.JSpinner topSpinner;
    private javax.swing.JCheckBox turboFirstPassCheckbox;
    private javax.swing.JRadioButton variableFrameRateRadio;
    private javax.swing.JComboBox videoFrameComboBox;
    private javax.swing.JPanel videoPanel;
    // End of variables declaration//GEN-END:variables
}
